---
# tasks file for roles/webserver
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: latest

    - name: Ensure nginx is started at boot
      ansible.builtin.service:
        name: nginx
        enabled: true

    - name: create web root
      ansible.builtin.file:
        path: /var/www/example.internal/html
        state: directory
        owner: root
        group: root
        mode: '0755'
      
    - name: Ensure the /etc/pki/nginx directory exists
      ansible.builtin.file:
        path: /etc/pki/nginx
        state: directory
        mode: "0755"
        owner: root

    - name: Ensure we have a /etc/pkig/nginx/private directory
      ansible.builtin.file:
        path: /etc/pki/nginx/private
        state: directory
        mode: "0700"
        owner: root

    - name: Ensure we have necessary software installed
      ansible.builtin.package:
        name: python3-cryptography
        state: present

    - name: Ensure we have a private key for our certificate
      community.crypto.openssl_privatekey:
        path: /etc/pki/nginx/private/server.key

    - name: Create a self-signed certificate
      community.crypto.x509_certificate:
        path: /etc/pki/nginx/server.crt
        privatekey_path: /etc/pki/nginx/private/server.key
        provider: selfsigned


    - name: Copy HTTPS configuration to nginx
      ansible.builtin.copy:
        src: https.conf
        dest: /etc/nginx/conf.d/https.conf
        owner: root
        group: root
        mode: '0644'
      register: resultconf
      notify: Reload nginx

    - name: deploy nginx Config
      ansible.builtin.template:
        src: example.internal.conf.j2
        dest: /etc/nginx/conf.d/example.internal.conf
        owner: root
        group: root
        mode: '0644'
      notify: Reload nginx

    - name: Upload index.html
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/example.internal/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Add web users
      vars:
        web_users:
        - name: alovelace
          groups: ['wheel', 'audio', 'video']
        - name: aturing
          groups: ['tape']
        - name: edijkstra
          groups: ['tcpdump']
        - name: ghopper
          groups: ['wheel', 'audio']
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups | join(',') }}"
        append: true
        state: present
      loop: "{{ web_users }}"