---
    - name: Uninstall all our favorite software
      hosts: all
      tasks:
        - name: Ensure vim, bash-completion, and qemu-guest-agent are uninstalled
          become: true
          ansible.builtin.package:
            name: vim,bash-completion,qemu-guest-agent
            state: absent
