---
    - name: Configure HTTPS for nginx
      hosts: web
      become: true
      tasks:
        - name: Copy HTTPS configuration to nginx
          ansible.builtin.copy:
            src: files/https.conf
            dest: /etc/nginx/conf.d/https.conf
            owner: root
            group: root
            mode: '0644' 
        - name: Ensure nginx service is restarted
          ansible.builtin.service:
            name: nginx
            state: restarted
