---
    - name: copy all md files to deploy
      hosts: db
      become: true

      tasks:
        - name: Copy all .md files to deploy directory
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: /home/deploy/
            owner: deploy
            group: deploy
            mode: '0644'
          with_fileglob:
            - "files/*.md"