---
    - name: Config firewall on web
      hosts: web
      become: true  
      tasks:
        - name: Install firewalld and python3-firewall
          ansible.builtin.package:
            name:
              - firewalld
              - python3-firewall
            state: present

        - name: Ensure firewalld is running and enabled
          ansible.builtin.service:
            name: firewalld
            state: started
            enabled: true

        - name: Allow HTTP service
          ansible.posix.firewalld:
            service: http
            permanent: true
            state: enabled
            immediate: yes
          
        - name: Allow HTTPS service
          ansible.posix.firewalld:
            service: https
            permanent: true
            state: enabled
            immediate: yes
    
    - name: Config firewall on db server
      hosts: db
      become: true
      tasks:
        - name: Install firewalld and python3-firewall
          ansible.builtin.package:
            name:
            - firewalld
            - python3-firewall
            state: present

        - name: Ensure firewalld is running and enabled
          ansible.builtin.service:
            name: firewalld
            state: started
            enabled: true
        
        - name: Allow MySQL service
          ansible.posix.firewalld:
            service: mysql
            permanent: true
            state: enabled
            immediate: yes